name: brianhscott
favicon: null
layout_spectrum: 0.16664169705472887
typography_spectrum: 0.2963703735731542
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#808080'
    - '#d99f00'
    - '#7e1e0f'
  brandStrength: 0.25
  lightness: 0.15739422012120485
  saturation: 0.8905252979602665
  rhythmicContrast: 0.4827334131114185
purpose: []
